# Generated by Django 3.2.7 on 2021-09-23 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('status', models.TextField(blank=True, max_length=100)),
                ('location', models.TextField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='pics')),
            ],
        ),
    ]
